name: Autopep static analysis

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8
    - name: Autopep8 format analysis 
      run: |
        find hw2/ -type f -name '*.py' | xargs -I {} sh -c '
          if autopep8 --diff "{}" | grep -q .; then
            echo "{}: Failed"
            exit 1
          else
            echo "{}: Passed"
          fi
        '